name: Deploy
run-name: Deploy on ${{ github.ref_name }})

on:
  push:
    branches:
      - master
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend
        uses: docker/build-push-action@v6
        if: github.actor == 'github-actions[bot]' && contains(github.event.head_commit.message, 'update') && contains(github.event.head_commit.message, 'frontend')
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wink-official-frontend:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wink-official-frontend:buildcache-${{ github.ref_name }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wink-official-frontend:buildcache-${{ github.ref_name }}

      - name: Build backend
        uses: docker/build-push-action@v6
        if: github.actor == 'github-actions[bot]' && contains(github.event.head_commit.message, 'update') && contains(github.event.head_commit.message, 'backend')
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wink-official-backend:${{ github.ref_name }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wink-official-frontend:buildcache-${{ github.ref_name }}
          cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/wink-official-frontend:buildcache-${{ github.ref_name }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH Connect (master)
        uses: appleboy/ssh-action@v1.0.3
        if: github.ref_name == 'master'
        with:
          host: ${{ secrets.SSH_MASTER_HOST }}
          username: ${{ secrets.SSH_MASTER_USERNAME }}
          key: ${{ secrets.SSH_MASTER_KEY }}
          script: |
            if [ ! -d "./wink-official-deploy" ]; then
              echo "Error: wink-official-deploy directory does not exist."
              return 1
            fi
            
            if [ ! -d "./deploy" ]; then
              echo "Error: deploy directory does not exist."
              return 1
            fi
            
            cd ./wink-official-deploy
            
            current_branch=$(git symbolic-ref --short HEAD)
            if [ "$current_branch" != "master" ]; then
              git checkout master
            fi
            
            git pull origin master
            
            docker compose pull
            docker compose down
            docker compose up -d

      - name: SSH Connect (develop)
        uses: appleboy/ssh-action@v1.0.3
        if: github.ref_name == 'develop'
        with:
          host: ${{ secrets.SSH_DEVELOP_HOST }}
          username: ${{ secrets.SSH_DEVELOP_USERNAME }}
          key: ${{ secrets.SSH_DEVELOP_KEY }}
          script: |
            if [ ! -d "./wink-official-deploy" ]; then
              echo "Error: wink-official-deploy directory does not exist."
              return 1
            fi
            
            if [ ! -d "./deploy" ]; then
              echo "Error: deploy directory does not exist."
              return 1
            fi
            
            cd ./wink-official-deploy
            
            current_branch=$(git symbolic-ref --short HEAD)
            if [ "$current_branch" != "develop" ]; then
              git checkout develop
            fi
            
            git pull origin develop
            
            docker compose pull
            docker compose down
            docker compose up -d
